/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 10.04.2026 21:38:03

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1472;
#else
constexpr int kTensorArenaSize = 448;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,13 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data1[10] = { -0.13789981603622437, 0, -0.039907775819301605, 0.2783045768737793, -0.10679852962493896, 0.22186720371246338, 0.14045514166355133, -0.092801220715045929, -0.081267707049846649, -0.1880364865064621, };
const TfArray<1, int> tensor_dimension1 = { 1, { 10 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data2[20] = { -0.03000994399189949, 0.010145816020667553, -0.074704840779304504, -0.051575172692537308, -0.35258957743644714, -0.026727085933089256, -0.082800805568695068, 0.091848887503147125, -0.27788019180297852, 0, 0.089996740221977234, 0.23130054771900177, 0, -0.073257096111774445, -0.21433748304843903, 0.011465428397059441, 0.094563201069831848, -0.11217313259840012, 0.034381113946437836, 0.2652772068977356, };
const TfArray<1, int> tensor_dimension2 = { 1, { 20 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data3[4] = { -0.15131817758083344, -0.066478058695793152, 0.08137812465429306, 0.14656311273574829, };
const TfArray<1, int> tensor_dimension3 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data4[20*13] = { 
  -0.031791146844625473, -0.02888728491961956, -0.063101410865783691, 0.31764876842498779, 0.089063368737697601, 0.1741243302822113, 0.090381696820259094, -0.29975137114524841, 0.10933436453342438, -0.36608439683914185, -0.043198075145483017, 0.12010987848043442, -0.40156802535057068, 
  -0.44181546568870544, -0.20507188141345978, 0.18230943381786346, 0.12715053558349609, 0.012800495140254498, 0.023613851517438889, 0.095739349722862244, 0.10021734237670898, 0.15817421674728394, 0.34408912062644958, -0.28929463028907776, 0.14423005282878876, 0.047957465052604675, 
  0.21820704638957977, 0.9438595175743103, -0.13822335004806519, -1.1762228012084961, -1.5110580921173096, 0.12447986751794815, 0.57974845170974731, -0.31250062584877014, 0.33074304461479187, 0.88950705528259277, -0.39419448375701904, 0.10183385014533997, 0.046442441642284393, 
  -0.40261170268058777, 0.16552655398845673, -0.27641633152961731, 0.19900980591773987, -0.063943840563297272, 0.19108445942401886, -0.094465501606464386, 0.35516893863677979, 0.15634122490882874, -0.408692866563797, 0.289267897605896, 0.28323438763618469, 0.15114612877368927, 
  0.14822244644165039, -1.8615807294845581, -0.070512533187866211, -1.2597912549972534, -2.4718389511108398, -0.058025442063808441, 0.49830159544944763, -0.51747977733612061, -0.87329328060150146, -0.53543800115585327, -0.71216273307800293, -0.53856885433197021, -0.46522676944732666, 
  -0.15266062319278717, 0.28929737210273743, 0.047925736755132675, -0.045026849955320358, -0.1692158579826355, -0.36087983846664429, 0.014128288254141808, 0.39351764321327209, -0.1904522031545639, 0.065152622759342194, -0.41998568177223206, -0.17887808382511139, -0.44283118844032288, 
  0.16600829362869263, -2.6225564479827881, -0.40568536520004272, 0.30583122372627258, 0.83496552705764771, -0.6443939208984375, -0.40197494626045227, 0.82736623287200928, -0.37026539444923401, -1.2844964265823364, -0.18582646548748016, -0.32465493679046631, -0.4487055242061615, 
  0.25898998975753784, 3.1216256618499756, 0.60136955976486206, 0.49952715635299683, 0.84883898496627808, -0.14137458801269531, -0.047963798046112061, -0.11432861536741257, 0.25631329417228699, 1.5434023141860962, 0.20622460544109344, 0.80538713932037354, 0.063054680824279785, 
  0.14543862640857697, -2.3937332630157471, -0.069363623857498169, -0.42665871977806091, -1.0500004291534424, 0.33395010232925415, -0.063566453754901886, -0.19471918046474457, -0.54821902513504028, -1.2365784645080566, -0.40747764706611633, -0.26778298616409302, -0.11098744720220566, 
  -0.35341614484786987, 0.18976640701293945, -0.35917356610298157, -0.027462154626846313, -0.24570614099502563, 0.25111615657806396, -0.38549080491065979, -0.0025837421417236328, -0.23160570859909058, -0.42587727308273315, -0.36126607656478882, -0.29042705893516541, -0.42452505230903625, 
  0.33882218599319458, 3.1563279628753662, 0.64947986602783203, -0.46624273061752319, -0.3637707531452179, -0.27169042825698853, 0.210626021027565, -0.29584380984306335, 0.25814792513847351, 1.2665263414382935, -0.10358849167823792, 0.45336633920669556, 0.38286969065666199, 
  -0.018655462190508842, 5.470362663269043, 0.80784904956817627, 0.83667153120040894, 1.9905204772949219, -0.97939300537109375, -0.0049583031795918941, -0.099447451531887054, 1.0307481288909912, 1.1940268278121948, 0.94854837656021118, 1.0581717491149902, 0.40459108352661133, 
  -0.1943180114030838, -0.40412119030952454, 0.0044142603874206543, -0.1357327401638031, 0.25638794898986816, -0.36510401964187622, -0.2525297999382019, -0.41117265820503235, -0.34211620688438416, 0.20266932249069214, -0.098162204027175903, -0.39184346795082092, 0.10384207963943481, 
  0.063539780676364899, -3.42661452293396, -0.48578500747680664, 0.33112853765487671, 1.0378783941268921, 0.33018118143081665, -0.50491917133331299, 0.85587483644485474, -0.37072977423667908, -1.2833178043365479, -0.16117860376834869, -0.25335592031478882, -0.027115359902381897, 
  0.2737390398979187, -3.632272481918335, -0.4352051317691803, 0.1460227370262146, 0.22443363070487976, -0.37161257863044739, -0.37083807587623596, 0.42261654138565063, -0.22524163126945496, -1.224698543548584, 0.051001932471990585, -0.89259326457977295, -0.82739168405532837, 
  -0.0028719643596559763, 2.2245969772338867, -0.072592787444591522, -1.1461097002029419, -1.8729482889175415, 0.45992052555084229, 0.29117608070373535, -0.58619564771652222, 0.23326516151428223, 1.387438178062439, 0.028098959475755692, 0.35018590092658997, 0.22673919796943665, 
  0.0043967231176793575, 2.6500139236450195, -0.017561711370944977, 1.3454810380935669, 3.5049769878387451, -0.91504871845245361, -0.81072282791137695, 0.30078122019767761, 0.63306236267089844, -0.45284414291381836, 0.008759714663028717, 0.18500974774360657, -0.25675138831138611, 
  -0.18991941213607788, 0.0954580157995224, 0.26162436604499817, 0.18875645101070404, 0.22070248425006866, -0.24367688596248627, -0.27709963917732239, 0.24188067018985748, 0.033962458372116089, -0.16575996577739716, -0.26121973991394043, 0.2996983528137207, -0.26086345314979553, 
  -0.32380485534667969, -0.074854038655757904, 0.25876668095588684, -0.38076421618461609, 0.2386411726474762, 0.068702138960361481, -0.24102264642715454, -0.0059277145192027092, 0.022089311853051186, -0.1156640499830246, -0.35619884729385376, -0.12822610139846802, -0.32919329404830933, 
  -0.15331929922103882, 0.23720227181911469, 0.074223726987838745, -0.015600155107676983, -0.12732274830341339, 0.058670904487371445, 0.32168561220169067, 0.11394598335027695, 0.4598105251789093, 0.42821931838989258, -0.15874132513999939, 0.51330697536468506, 0.51828277111053467, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 20,13 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data5[10*20] = { 
  0.12526106834411621, 1.2911427021026611, -0.27528935670852661, 0.049101203680038452, 0.36859336495399475, 0.05985337495803833, 0.41975930333137512, -0.43165621161460876, -0.033549360930919647, -0.19483354687690735, 0.062781229615211487, -0.32735928893089294, 0.24257105588912964, 0.41821932792663574, 0.19265903532505035, -0.43480703234672546, 0.053837243467569351, 0.37610813975334167, -1.2884101867675781, 0.35043421387672424, 
  -0.21513541042804718, -0.43652644753456116, 0.25989925861358643, 0.25670373439788818, 0.20556908845901489, -0.15646842122077942, -0.19914223253726959, -0.36983609199523926, -0.35554879903793335, 0.069873809814453125, -0.20073221623897552, -0.2023371160030365, 0.2409820556640625, 0.084498703479766846, 0.26755255460739136, 0.3430597186088562, -0.19190970063209534, 0.13136303424835205, -0.1693665087223053, -0.11774033308029175, 
  -0.086540102958679199, -0.48266500234603882, -0.011426568031311035, 0.40303337574005127, -0.18503651022911072, -0.22609998285770416, -0.13627669215202332, -0.15812249481678009, -0.15676471590995789, -0.043710947036743164, -0.067290909588336945, -0.068002477288246155, -0.081969767808914185, -0.36335638165473938, -0.050489902496337891, -0.26666605472564697, 0.12797077000141144, -0.37735411524772644, -0.38322222232818604, -0.46319618821144104, 
  0.22499942779541016, 0.18368175625801086, 0.31342530250549316, 0.052891075611114502, -0.29031220078468323, 0.32044690847396851, -0.27153992652893066, -0.21223887801170349, -0.14580246806144714, 0.28100210428237915, 0.34208399057388306, 0.47694489359855652, -0.28030186891555786, -0.38947296142578125, -0.063941247761249542, -0.14906613528728485, -0.092388950288295746, -0.10674548149108887, 0.43568414449691772, 0.6097143292427063, 
  -0.17334240674972534, 0.12057542055845261, -0.4820600152015686, -0.12990015745162964, -0.44800320267677307, 0.24035236239433289, -0.24977576732635498, -0.028816288337111473, -0.51348012685775757, 0.23458927869796753, 0.20572714507579803, -0.033071137964725494, -0.077009856700897217, 0.079127185046672821, -0.017315374687314034, -0.50158286094665527, -0.35882019996643066, 0.29320278763771057, 0.19698028266429901, 0.19980096817016602, 
  -0.30585864186286926, 0.38530495762825012, -0.32690134644508362, 0.25209605693817139, -0.19301633536815643, -0.41971859335899353, -0.099147297441959381, 0.26498538255691528, -0.49741128087043762, -0.17979496717453003, 0.24310815334320068, 0.34020677208900452, -0.19458532333374023, 0.25281530618667603, -0.16103710234165192, -0.3096415102481842, -0.27882346510887146, 0.33287972211837769, -0.2629101574420929, 0.23202468454837799, 
  0.38197445869445801, 0.14123286306858063, -0.23898999392986298, -0.26115092635154724, 0.28481441736221313, 0.27403214573860168, 0.03277282789349556, -0.1244800016283989, -0.12857846915721893, 0.0096309185028076172, 0.23163565993309021, 0.67246812582015991, -0.27470189332962036, -0.15407232940196991, 0.023475794121623039, -0.10357985645532608, 0.54107034206390381, -0.015217771753668785, -0.21694526076316833, -0.045853924006223679, 
  -0.057526230812072754, 0.2537497878074646, 0.12764376401901245, 0.17893220484256744, -0.11729351431131363, 0.30298417806625366, 0.30068522691726685, -0.51874685287475586, 0.34719303250312805, -0.11473512649536133, -0.31819134950637817, 0.33978107571601868, 0.25406181812286377, -0.1811864823102951, -0.43414199352264404, 0.14506527781486511, -0.14844262599945068, -0.06609509140253067, 0.0056850123219192028, 0.2266223132610321, 
  0.20891351997852325, 0.039086330682039261, 0.19028845429420471, 0.10424406081438065, 0.3343806266784668, 0.10111888498067856, -0.44843015074729919, -0.12289343029260635, -0.11197889596223831, 0.047066181898117065, 0.35356652736663818, -0.10331472754478455, -0.018651306629180908, -0.45713227987289429, -0.15827378630638123, 0.65591859817504883, -1.1280266046524048, 0.17842508852481842, -0.23531275987625122, -0.32449668645858765, 
  0.13866981863975525, -0.37377834320068359, -0.099296346306800842, -0.05939275398850441, 0.27413532137870789, 0.35944762825965881, -0.12064515054225922, -0.0094598280265927315, 0.26000484824180603, -0.35648933053016663, -0.27235874533653259, -0.17840032279491425, -0.28586220741271973, -0.26513001322746277, 0.17192219197750092, -0.041030652821063995, -0.25076082348823547, 0.25191870331764221, -0.035507213324308395, 0.19029594957828522, 
};
const TfArray<2, int> tensor_dimension5 = { 2, { 10,20 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) float tensor_data6[4*10] = { 
  0.30615788698196411, 0.37228477001190186, 0.64017331600189209, -0.30848541855812073, 0.018024679273366928, -0.5131801962852478, -0.54687154293060303, -0.18728598952293396, 0.65027767419815063, 0.18617904186248779, 
  0.30308741331100464, -0.11675214767456055, -0.49895977973937988, -0.58844798803329468, -0.47684395313262939, -0.52323037385940552, 0.13113033771514893, 0.093306556344032288, -0.16120277345180511, -0.053477227687835693, 
  -0.40222540497779846, 0.55127537250518799, -0.41215449571609497, -0.60188442468643188, 0.089672677218914032, -0.54975926876068115, 0.49617081880569458, 0.25065699219703674, 0.30412828922271729, -0.1671430915594101, 
  -0.19670389592647552, -0.11847734451293945, -0.00088191981194540858, 0.95577734708786011, 0.39839193224906921, -0.027862239629030228, 0.23373620212078094, -0.099149413406848907, -0.59288734197616577, -0.70869505405426025, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 4,10 } };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,4,2 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,5,1 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,6,3 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension0, 52, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 40, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 80, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 16, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 1040, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 800, },
{ kTfLiteMmapRo, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 160, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 80, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 80), (TfLiteIntArray*)&g0::tensor_dimension8, 40, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 16, },
{ kTfLiteArenaRw, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 16, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = kTfLiteFloat32;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization.type = kTfLiteNoQuantization;

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = kTfLiteFloat32;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_957717_3_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_957717_3_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_957717_3_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_957717_3_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_957717_3_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
